a=input('Ho ten: ')
b=int(input('So ngay cong: '))
c=int(input('Don gia ngay cong: '))
d=float(input('He so phu cap: '))
e=int(input('Tam ung: '))
f=round(c*b*d,1)
h=round(f-e,1)
print('Nhan vien '+str(a)+','+' Co tien Luong='+ str(f)+','+' Tam ung='+str(e)+' va Thuc linh='+str(h))